spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: ${SECURITY_PROTOCOL:PLAINTEXT}

  cloud:
    stream:
      function.definition: process
      bindings:
        process-in-0:
          destination: aim-visit
        process-out-0:
          destination: encounter-fhir
      kafka:
        streams:
          binder:
            applicationId: visit-to-fhir
            configuration:
              compression.type: gzip
              max.request.size: 5242880
            deserializationExceptionHandler: sendToDlq

fhir:
  systems:
    encounterId: "https://fhir.diz.uni-marburg.de/NamingSystem/identifier/EncounterId"
  generateNarrative: false
  useConditionalUpdate: false

services:
  pseudonymizer:
    url: "http://localhost:5000/fhir"

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.visittofhir: ${LOG_LEVEL:info}
