spring:
  jmx:
    enabled: true
  kafka:
    bootstrapServers: ${BOOTSTRAP_SERVERS:localhost:9092}
    security.protocol: SSL
    ssl:
      trust-store-location: file://${user.dir}/dev/ssl/patient-to-fhir.truststore.jks
      trust-store-password: ssl-test
      key-store-location: file://${user.dir}/dev/ssl/patient-to-fhir.keystore.jks
      key-store-password: ssl-test
      key-password: ssl-test
    properties:
      ssl.endpoint.identification.algorithm:


  cloud:
    stream:
      function.definition: process
      bindings:
        process-in-0:
          destination: aim-patient
        process-out-0:
          destination: patient-fhir
      kafka:
        streams:
          binder:
            applicationId: patient-to-fhir
            configuration:
              compression.type: gzip
              max.request.size: 5242880
            deserializationExceptionHandler: sendToDlq

fhir:
  systems:
    patientId: "https://fhir.diz.uni-marburg.de/NamingSystem/identifier/PatientId"
  generateNarrative: false
  useConditionalUpdate: false

services:
  pseudonymizer:
    url: "http://localhost:5000/fhir"

  endpoints:
    web:
      exposure:
        include: "health, prometheus, info, metric"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.kafka.config: info
    de.unimarburg.diz.patienttofhir: debug
server:
  port: 0
