INSERT INTO public.patient_class (id, description) VALUES ('E', 'Notfall');
INSERT INTO public.patient_class (id, description) VALUES ('O', 'Ambulant (en)');
INSERT INTO public.patient_class (id, description) VALUES ('P', 'Voraufnahme');
INSERT INTO public.patient_class (id, description) VALUES ('R', 'Wiederholungspatient');
INSERT INTO public.patient_class (id, description) VALUES ('B', 'Geburtshilfe');
INSERT INTO public.patient_class (id, description) VALUES ('S', 'Stationär');
INSERT INTO public.patient_class (id, description) VALUES ('A', 'Ambulant');
INSERT INTO public.patient_class (id, description) VALUES ('C', 'Account');
INSERT INTO public.patient_class (id, description) VALUES ('N', 'Nicht anwendbar');
INSERT INTO public.patient_class (id, description) VALUES ('U', 'Unbekannt');
INSERT INTO public.patient_class (id, description) VALUES ('TK', 'Tagesklinische Behandlung');
INSERT INTO public.patient_class (id, description) VALUES ('I', 'Stationär (en)');
INSERT INTO public.patient_class (id, description) VALUES ('V', 'Vorstationär');
INSERT INTO public.patient_class (id, description) VALUES ('NS', 'Nachstationär');
INSERT INTO public.patient_class (id, description) VALUES ('TS', 'Teilstationäre Behandlung');
INSERT INTO public.patient_class (id, description) VALUES ('VS', 'Vollstationäre Behandlung');